default:
	@echo "ATTENZIONE! Nessun comando eseguito"

hook:
	@echo "Script: installazione/aggiornamento hooks iniziato"
	@rm -r ../.git/hooks
	@echo "Pulizia hooks vecchi completata"
	@cp -r hooks ../.git/hooks
	@echo "Script: installazione/aggiornamento hooks completato"