(function () {
	'use strict';

	/**
	 * Name: app/scripts/controllers/recipe/charts.ctrl.js
	 * Author: MashUp
	 * Mail. info@mashup-unipd.it
	 *
	 * Modify
	 * Version  Date        Author          Desc
	 * ==========================================================
	 * 0.0.1    2015-05-12  Tesser Paolo    code module
	 * -----------------------------------------------------------
	 *
	 */

	/**
	 * @ngdoc function
	 * @name app.controller:ChartsCtrl
	 * @description
	 * # ChartsCtrl
	 * Controller of the app
	 */

	var ChartsCtrl = function ($stateParams, recipeService, userService) {

		var vm = this;

		vm.heading = "";
		vm.metric = $stateParams.metric;
		vm.metric2 = $stateParams.metric2;
		vm.metric3 = $stateParams.metric3;
		vm.cat = $stateParams.cat;
		vm.type = $stateParams.type;
		vm.getGraph = [];
		vm.noGraphData = false;
		vm.addedFavourite = false;
		vm.failedAdd = false;
		vm.addToFavourites = addToFavourites;

		var parameter;
		var graphPromise;

		if (vm.metric2 == "") {

			parameter = {
				cat: vm.cat,
				type: vm.type,
				value: vm.metric
			};

			vm.heading="Graphs generated by the metric " + vm.metric;

			graphPromise = recipeService.generateViews(parameter);
		}
		else{


			if (vm.metric3 == "") {

				parameter = {
					cat: vm.cat,
					type: vm.type,
					value: [vm.metric,vm.metric2]
				};

				vm.heading = "Comparison between the metrics " + vm.metric + ' and ' + vm.metric2;
			}else{
				parameter = {
					cat: vm.cat,
					type: vm.type,
					value: [vm.metric, vm.metric2, vm.metric3]
				};

				vm.heading = "Comparison between the metrics " + vm.metric + ', ' + vm.metric2 + ' and ' + vm.metric3;
			}

			graphPromise = recipeService.generateCompare(parameter);

		}

		graphPromise
			.then(function(list){
				vm.getGraph = list;
				vm.noGraphData = false;

			}, function(error, response){
				console.log(error + ' ' + JSON.stringify(response));
				vm.noGraphData = true;
			});


		function addToFavourites(info){
			var promise= userService.addFavourite(parameter,info);
			promise
				.then(function(){
					vm.addedFavourite = true;
				},function(){
					vm.failedAdd = true;
				})
		}
	};

	ChartsCtrl.$inject = ['$stateParams','recipeService','userService'];

	angular.module('app').controller('ChartsCtrl', ChartsCtrl);

})();
